// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiqtcvtbltxsiptwuheb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpcXRjdnRibHR4c2lwdHd1aGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTI3OTQsImV4cCI6MjA2OTc4ODc5NH0.D_33TvehLgkjJb4j6xWqT_3nJgh-c2tPGui5NvcrWfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});